# Generated by Django 4.2.5 on 2023-10-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='discount',
            field=models.CharField(max_length=10),
        ),
    ]
